name: Autograding Tests
on:
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Autograding
      id: autograder
      run: |
        output=$(./lab1/autograder.sh)
        echo "grade=$output" >> $GITHUB_OUTPUT
    - name: Report
      run: |
        echo "${{steps.autograder.outputs.grade}}"